Outdated doc?
calling `@client.available_phone_numbers` gives error:
`undefined method `available_phone_numbers' for #<Twilio::REST::Client:0x000001022cc218>`
So it looks like it should be `@client.account.available_phone_numbers`